    
    SELECT record_id,name_code,common_name,language,country,reference_id,database_id,is_infraspecies INTO OUTFILE '/tmp/common_names.csv' FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '\\' LINES TERMINATED BY '\n' FROM common_names;
    SELECT database_name_displayed, record_id, database_name, database_full_name, web_site, replace(organization,'"','\''), contact_person, taxa, taxonomic_coverage, replace(replace(abstract,',','%2C'),'"','\''), version, release_date, SpeciesCount, SpeciesEst, authors_editors, accepted_species_names, accepted_infraspecies_names, species_synonyms,  infraspecies_synonyms, common_names, total_names, is_new INTO OUTFILE '/tmp/databases.csv' FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '\\' LINES TERMINATED BY '\n' FROM `databases` d;
    SELECT record_id, name_code, replace(distribution,",","%2C") INTO OUTFILE '/tmp/distribution.csv' FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '\\' LINES TERMINATED BY '\n' FROM distribution;
    SELECT record_id, hierarchy_code, kingdom, phylum, class, 'order', family, superfamily, family_common_name, database_name, is_accepted_name, database_id INTO OUTFILE '/tmp/families.csv' FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '\\' LINES TERMINATED BY '\n' FROM families;
    SELECT taxon,species_count INTO OUTFILE '/tmp/hard_coded_species_totals.csv' FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '\\' LINES TERMINATED BY '\n' FROM hard_coded_species_totals;
    SELECT rank, accepted_names_only,name INTO OUTFILE '/tmp/hard_coded_taxon_lists.csv' FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '\\' LINES TERMINATED BY '\n' FROM hard_coded_taxon_lists;
    SELECT record_id, author, year, replace(replace(title,",","%2C"),'"','\'') , replace(source,",","%2C"), database_id INTO OUTFILE '/tmp/references.csv' FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '\\' LINES TERMINATED BY '\n' FROM `references` r;
    SELECT record_id,name_code,reference_type,reference_id INTO OUTFILE '/tmp/scientific_name_references.csv' FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '\\' LINES TERMINATED BY '\n' FROM scientific_name_references;
    SELECT record_id,name_code,web_site,genus,species,infraspecies,infraspecies_marker,author,accepted_name_code,comment,scrutiny_date,sp2000_status_id,database_id,specialist_id,family_id,is_accepted_name INTO OUTFILE '/tmp/scientific_names.csv' FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '\\' LINES TERMINATED BY '\n' FROM scientific_names;
    SELECT record_id,taxa_id,words INTO OUTFILE '/tmp/simple_search.csv' FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '\\' LINES TERMINATED BY '\n' FROM simple_search;
    SELECT record_id,sp2000_status INTO OUTFILE '/tmp/sp2000_statuses.csv' FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '\\' LINES TERMINATED BY '\n' FROM sp2000_statuses;
    SELECT record_id,specialist_name,database_id INTO OUTFILE '/tmp/specialists.csv' FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '\\' LINES TERMINATED BY '\n' FROM specialists;
    SELECT record_id,lsid,name,name_with_italics,taxon,name_code,parent_id,sp2000_status_id,database_id,is_accepted_name,is_species_or_nonsynonymic_higher_taxon INTO OUTFILE '/tmp/taxa.csv' FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '\\' LINES TERMINATED BY '\n' FROM taxa;
    
